version: "3.8"

services:
    db:
        image: "postgres"
        container_name: database
        env_file:
            - .env
        # volumes:
            # - ./volume/postgres:/var/lib/postgresql/data/
        ports: 
            - 5432:5432